### ISSUE TITLE
Method prepareSetCounter in CardTransactionManager doesn't support numCounter equals to zero

### ISSUE THREAD

**Issue by JulienDidier38** [eclipse/keyple-card-calypso-java-lib#100]
Hello,

We try to use the method `prepareSetCounter` of class `CardTransactionManager` on a card CD97V2 (which has "physical" counter files, not simulated).
So we pass as parameter for numCounter the value 0 (we don't have indice for this type of counter not simulated) and we receive an IllegalArgumentException with message "numCounter must be greater than 1".
Like methods prepareIncrease or prepareDecrease, we expect this method support the 0 value for numCounter parameter.

**Comment by andrei-cristea** [comment]
Hi @JulienDidier38,

We are pleased to inform you that this issue has been addressed in the recent release [2.3.8](https://github.com/eclipse/keyple-card-calypso-java-lib/releases/tag/2.3.8).

Best regards
