### ISSUE TITLE
For Calypso Basic application type it returns Rev 3.2 supported

### ISSUE THREAD

**Issue by BhushanPatil555** [eclipse/keyple-card-calypso-java-lib#26]
Hello Sir, 
Good Morning

Hope you are doing fine.

For application type 98h which is for Calypso Basic as per 191011-CalypsoBasic version 1.1.
The Keyple 2.0 java example consider the Rev 3.2 is supported and  eventually Calypso Basic card throws as 6B00 error(P1 or P2 not supported). 

Code snippet, 
```
isExtendedModeSupported = (applicationType & APP_TYPE_CALYPSO_REV_32_MODE) != 0;
 Here, private static final byte APP_TYPE_CALYPSO_REV_32_MODE = 0x08;
```
Does this keyple 2.0 library support only prime and light product or does it have support basic too?

Revert for any additional info.

Thanks & Regards, 
Bhushan

**Comment by jeanpierrefortune** [comment]
Hi Bhushan,
The library is expected to work with Calypso Basic.
It looks like the code you're pointing to doesn't take that into account.
We will fix this identification issue as soon as I can discuss it further with the other team members.

Regards,
Jean-Pierre

**Comment by pterr** [comment]
Thanks again Bhushan, the current Calypso lib doesn't handle correctly the Basic option => it will be fixed in the coming days.

**Comment by BhushanPatil555** [comment]
Hello Jean, 

Thank you for fixing the issue.

Jean one observation, as I was referring to the java examples from link : https://github.com/eclipse/keyple-java-example.
In this repo the new version of calypso-java-lib is not updated with above fix.

May I request you to do necessary release.

Thanks & Regards
Bhushan

**Comment by jeanpierrefortune** [comment]
Hello Bhushan,

We have updated the different libraries that are involved.

You will find [here](https://keyple.org/projects-dashboard/) and in the CHANGELOG.md files at the root of the repositories the information and details concerning these evolutions.

Regards,
Jean-Pierre

**Comment by BhushanPatil555** [comment]
Thanks Jean.

It works fine.

A small observation w.r.t. Intellij IDEA 2021.2.3, IDE gives a message with JDK 16 not compatible with Gradle 6.8.3. This lead to change in Gradle properties.

I am not sure this is more related to IDEA/gradle or anything else. Just want to bring it to your notice.

Regards, 
Bhushan
